//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegeMst()
        {
            this.TeacherCollegeMapps = new HashSet<TeacherCollegeMapp>();
        }
    
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> StateID { get; set; }
        public string CollegeDesc { get; set; }
    
        public virtual StateMst StateMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherCollegeMapp> TeacherCollegeMapps { get; set; }
    }
}
