//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CollegeMst
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CollegeMst()
    {
        this.TeacherCollegeMapps = new HashSet<TeacherCollegeMapp>();
    }

    public int CollegeID { get; set; }
    public string CollegeName { get; set; }
    public Nullable<int> StateID { get; set; }
    public string CollegeDesc { get; set; }

    public virtual StateMst StateMst { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TeacherCollegeMapp> TeacherCollegeMapps { get; set; }
}

public partial class DepMst
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DepMst()
    {
        this.Enrollments = new HashSet<Enrollment>();
    }

    public int Dept_ID { get; set; }
    public string Dept_Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Enrollment> Enrollments { get; set; }
}

public partial class Enrollment
{
    public int EnrollmentID { get; set; }
    public Nullable<decimal> Salary { get; set; }
    public int Dept_ID { get; set; }
    public int TEACHERID { get; set; }
    public int StateID { get; set; }

    public virtual DepMst DepMst { get; set; }
    public virtual StateMst StateMst { get; set; }
    public virtual TeacherMst TeacherMst { get; set; }
}

public partial class StateMst
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public StateMst()
    {
        this.Enrollments = new HashSet<Enrollment>();
        this.CollegeMsts = new HashSet<CollegeMst>();
    }

    public int StateID { get; set; }
    public string State_Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Enrollment> Enrollments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CollegeMst> CollegeMsts { get; set; }
}

public partial class TeacherCollegeMapp
{
    public int Id { get; set; }
    public Nullable<int> CollegeID { get; set; }
    public Nullable<int> TeacherID { get; set; }

    public virtual CollegeMst CollegeMst { get; set; }
    public virtual TeacherMst TeacherMst { get; set; }
}

public partial class TeacherMst
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TeacherMst()
    {
        this.Enrollments = new HashSet<Enrollment>();
        this.TeacherCollegeMapps = new HashSet<TeacherCollegeMapp>();
    }

    public int TeacherID { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string Emp_Code { get; set; }
    public string DateOfBirth { get; set; }
    public string JoiningDate { get; set; }
    public string Image { get; set; }
    public string Gender { get; set; }
    public string EmailID { get; set; }
    public string MobileNo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Enrollment> Enrollments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TeacherCollegeMapp> TeacherCollegeMapps { get; set; }
}
