//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherCollegeMapp
    {
        public int Id { get; set; }
        public Nullable<int> CollegeID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        public virtual CollegeMst CollegeMst { get; set; }
        public virtual TeacherMst TeacherMst { get; set; }
    }
}
